import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/base/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Drump Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="light">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
